// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3aQXK33FPyVGrcxFBF8BiPNv7MWRMEBI',
    appId: '1:754140581101:web:d049eefb641f3f45d750e4',
    messagingSenderId: '754140581101',
    projectId: 'lesap-status',
    authDomain: 'lesap-status.firebaseapp.com',
    storageBucket: 'lesap-status.appspot.com',
    measurementId: 'G-B4WG7WEWP5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKezBx49bCW6e3wXIJnOsOfsv9LZB1siQ',
    appId: '1:754140581101:android:18d84ef9350ae81ad750e4',
    messagingSenderId: '754140581101',
    projectId: 'lesap-status',
    storageBucket: 'lesap-status.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBACW0_mQwpX0m9YEVdiantS9_dvZpwY2g',
    appId: '1:754140581101:ios:cbcd3ab61032ab60d750e4',
    messagingSenderId: '754140581101',
    projectId: 'lesap-status',
    storageBucket: 'lesap-status.appspot.com',
    androidClientId: '754140581101-d036i2vfnthh1jk9rbr2dpasboq820an.apps.googleusercontent.com',
    iosClientId: '754140581101-vokuejeka651q46c7ib5conupsuo4h2f.apps.googleusercontent.com',
    iosBundleId: 'com.example.revisions1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3aQXK33FPyVGrcxFBF8BiPNv7MWRMEBI',
    appId: '1:754140581101:web:9633dce2dc5c098cd750e4',
    messagingSenderId: '754140581101',
    projectId: 'lesap-status',
    authDomain: 'lesap-status.firebaseapp.com',
    storageBucket: 'lesap-status.appspot.com',
    measurementId: 'G-NT9BJ9CEMX',
  );

}